# Generated by Django 5.1.6 on 2025-03-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0002_remove_productmodel_colors_productcolorstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.colormodel'),
        ),
    ]
